// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBENkupVLosqzbMoGmy8eI8qqGXzC-GXE8',
    appId: '1:189435347287:web:1f434e65459a9a22e53e12',
    messagingSenderId: '189435347287',
    projectId: 'capstone-project-a9296',
    authDomain: 'capstone-project-a9296.firebaseapp.com',
    storageBucket: 'capstone-project-a9296.firebasestorage.app',
    measurementId: 'G-WJNLT84WTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQITqHOMbfiFezjv2P5Idkf479f2pbt4',
    appId: '1:189435347287:android:9ed0358a6bf86e08e53e12',
    messagingSenderId: '189435347287',
    projectId: 'capstone-project-a9296',
    storageBucket: 'capstone-project-a9296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFrvjXtflgB4uFbhgVgciujyWMftKEDg',
    appId: '1:189435347287:ios:99332bbc71b97391e53e12',
    messagingSenderId: '189435347287',
    projectId: 'capstone-project-a9296',
    storageBucket: 'capstone-project-a9296.firebasestorage.app',
    iosClientId: '189435347287-g1fisfer3upq6063m80n9ckp579smj0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhFrvjXtflgB4uFbhgVgciujyWMftKEDg',
    appId: '1:189435347287:ios:99332bbc71b97391e53e12',
    messagingSenderId: '189435347287',
    projectId: 'capstone-project-a9296',
    storageBucket: 'capstone-project-a9296.firebasestorage.app',
    iosClientId: '189435347287-g1fisfer3upq6063m80n9ckp579smj0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBENkupVLosqzbMoGmy8eI8qqGXzC-GXE8',
    appId: '1:189435347287:web:feeeea6eb9900cc2e53e12',
    messagingSenderId: '189435347287',
    projectId: 'capstone-project-a9296',
    authDomain: 'capstone-project-a9296.firebaseapp.com',
    storageBucket: 'capstone-project-a9296.firebasestorage.app',
    measurementId: 'G-QNQSZZQNED',
  );
}
